version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 650251731217.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t flask-snowflake-app .  # Local image name
      - docker tag flask-snowflake-app:latest 650251731217.dkr.ecr.us-east-1.amazonaws.com/snowflake-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 650251731217.dkr.ecr.us-east-1.amazonaws.com/snowflake-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"flask-snowflake-app","imageUri":"650251731217.dkr.ecr.us-east-1.amazonaws.com/snowflake-app:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
